version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
    networks:
      - tasitracker
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: tasitracker
      POSTGRES_PASSWORD: tasitracker
      POSTGRES_DB: tasitracker
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - tasitracker
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - postgres
    networks:
      - tasitracker
volumes:
  postgres_data:
networks:
  tasitracker:
